jaoafa/jaoweb-docs

blog/discord-two-factor.md
縦長の画像がクソデカになって見づらいのでサイズを修正しました
=> 「Discordで二段階認証をする方法」の画像サイズを修正

blog/forge-commentary.md
=> ブログ記事「Forgeの導入解説【1.16.5版】」を筆記

blog/join-discord.md, server/rules/discord.md
=> Discordのロゴを新しいものに更新

server/beginners.md
各問い合わせフォーム（Discord、Googleフォーム）へのリンクはあったものの、問い合わせページへのリンクはなかったため追加。
=> 問い合わせページへのリンクを追加

blog/how-to-vote.md
・「両サイトはjaoが運営しているわけではない」の文章をわかりやすく
・次回投票可能時刻について追記
=> 投票解説ブログ記事の文章加筆修正

support/inquiry.md
・「Minecraft(Mojang)公式」だとわかりづらいので「Minecraft開発元(Mojang)」に変更。
・その他細かい部分の加筆修正。
=> お問い合わせページの文章加筆修正

server/guidelines/griefing.md
・チャットスパム行為について、「チャットに関するガイドライン」へのリンクを追加。
・その他、文章の軽微な修正。
=> 「迷惑行為の対応に関するガイドライン」文章の加筆・修正

support/inquiry.md
=> 「お問い合わせ」ページの修正

server/index.md
- close https://github.com/jaoafa/jaoweb/issues/25
[/server にアクセスすると 403 Forbidden がでる問題](https://jaoafa.com/server/) の暫定修正。
=> server/index.md の作成

server/policies/permissions.md
Community Regularの新設に伴い、情報を追加。
=> Community Regularの項目を追加

server/rules/index.md
=> Discord関連のルールについて追記

blog/join-discord.md
ブログ記事「jao Minecraft Server 公式Discordサーバへの参加方法」にあったDiscord招待リンクを更新
=> fix: Discord招待リンクの更新

.github/CODEOWNERS
普通にコードオーナーの構文間違えていました
内容が変わってるわけではないのでそのままマージしてしまいます
=> fix: CODEOWNERS syntax

.github/workflows/markdown-header-check.yml, .github/workflows/markdown-lintcheck-request.yml
=> fix: プルリク時にlintcheckが走らない問題の修正?

server/guidelines/index.md
=> ガイドライン-index 文章の修正

blog/202112-server-stop.md
・「MinecraftアカウントとDiscordアカウントの連携」について、特例措置に関する情報を追加しました。
=> サーバ一時停止についての記事において、軽微な追加・変更

blog/202202-server-restart.md
=> feat: サービス再開のお知らせを追加

server/policies/bans.md
=> change: GBanを削除&置き換え

server/guidelines/broadcasts.md
#134 より先行でこっちをマージしないとワークフローが落ち続けます
=> fix: 「撮影・動画配信に関するガイドライン」に説明ヘッダーを追加

blog/fabric-commentary.md
=> chore: ブログ記事「Fabricの導入解説」のアイキャッチ追加

blog/202208event.md
=> fix(202208event): Mod名の修正

server/policies/bans.md
=> Ban方針について、VBan時の他サービス利用制限について追加

server/rules/discord.md
表題のとおりです。
詳しくは変更箇所を確認してください。
close #173
=> Discordサーバのルールページについて、「jao Minecraft Server独自のDiscordルールである」旨を追記

.github/gen-page-preview/package-lock.json, .github/workflows/generate-page-preview-image.yml
=> fix: npm install -D @playwright/testがないと動かないらしい

server/profiles.md
=> fix:運営者情報ページについて、DiscordIDの仕様変更への対応

server/profiles.md
=> docs: 運営者情報を更新
